export { computeLeadContourWhole } from './lead'
export { computeBassContourWhole } from './bass'
export { computeFirstHarmonyContourWhole } from './firstHarmony'
export { computeSecondHarmonyContourWhole } from './secondHarmony'
export { computeLeadIntroContourWhole, computeNonLeadIntroRestContourWhole } from './intro'
