export { computeLeadContourPieces } from './lead'
export { computeFirstHarmonyContourPieces } from './firstHarmony'
export { computeSecondHarmonyContourPieces } from './secondHarmony'
export { computeBassContourPieces } from './bass'
export { computeLeadIntroContourPieces, computeNonLeadIntroRestContourPieces } from './intro'
